### ISSUE TITLE
Night mode switcher is broken on mobile layout.

### ISSUE THREAD

**Issue by ElegantMonkey** [ewhal/nyaa#172]
![screenshot_2017-05-07-21-56-04](https://cloud.githubusercontent.com/assets/5082637/25786731/2e2a1a42-3370-11e7-8da2-2e59e5c4ad51.png)

It's under the hamburger menu. I tried playing around with CSS but I just can't figure out Bootstrap.

**Comment by MasterCATZ** [comment]
does not even switch for me on local or pantsu.cat

**Comment by gensuihime** [comment]
What specifically do you mean when you say "broken"?

**Comment by ElegantMonkey** [comment]
@gensuihime,
1. It barely allows you to change theme, you need to "spam" the hamburger menu to toggle it. Can't test it right now because of 502 errors.
2. It breaks the layout.

It's probably caused by the position: fixed on the main CSS, because it isn't an native Bootstrap element on the navbar, but rather it's "hacked in", or so it seems.

**Comment by gensuihime** [comment]
I'd have to take a closer look but from experience it seems to occur due to lack of mobile consistency.  The position:fixed is likely breaking the layout as all the elements are squished into the mobile window but only working via spamming the button seems to be a different issue altogether. For now goto the three dots menu > Request Desktop Site and it should(?) work better.

**Comment by ElegantMonkey** [comment]
As I said, the site is down so I can't really tell. Maybe "spamming" isn't really the best way to say it, but my guess is that you need to hit the small part that doesn't intersect with the hamburger menu, just a guess though.

It's not that much of a serious issue, the site can be used normally, and using the desktop version sacrifices a lot of usability.

**Comment by kipukun** [comment]
This is fixed as hell, yo (on latest HEAD of course)
