### ISSUE TITLE
Some Subekei trackers are showing incorrect peers and (fake) seeds

### ISSUE THREAD

**Issue by ravenlord1** [ewhal/nyaa#18]
This is for Subekei

The trackers provided with the magnet link for Files 712278 and 711897 (picture 1) are showing incorrect (fake) seeds for the swarm and also the incorrect number of peers (pictures 2 and 3).  DHT seems to have it correct.  

However the same trackers for 1332531 (picture 4) are behaving properly (picture 5).  That leads me to believe that the trackers and torrent client are OK, but that there is something odd about how some of the files in the DB are being complied or indexed.

Windows 7, uTorrent 2.2.1, same results w/ and w/o VPN active.
![1](https://cloud.githubusercontent.com/assets/26584049/25720975/b38d3e3a-30c3-11e7-80be-8101ee6d8ffb.jpg)
![2](https://cloud.githubusercontent.com/assets/26584049/25720976/b3a99df0-30c3-11e7-8e7d-96988ed33ce5.jpg)
![3](https://cloud.githubusercontent.com/assets/26584049/25720978/b3b319b6-30c3-11e7-9b6a-896e9a56b0be.jpg)
![4](https://cloud.githubusercontent.com/assets/26584049/25720977/b3aca09a-30c3-11e7-9e6a-849066397884.jpg)
![5](https://cloud.githubusercontent.com/assets/26584049/25720979/b3ca4ef6-30c3-11e7-9121-4591b09d096a.jpg)

**Comment by S0X-LT** [comment]
Not a bug, not by the site at least. I just checked the first torrent and there doesn't seem to be any Seeds in the first place. That you see "seeds" but can't connect to them are either because:


1: You haven't opened your ports properly and can't connect to the Seeds
2: The Seeds stopped taking incoming connections, so it still reports "completed" to the tracker but are not uploading anything. 

I would also argue that they are fake seeders, but it is HIGHLY unlikely because they are public trackers, so it wouldn't make any sense.
