### ISSUE TITLE
Comment hidden under header when clicking said comment's link in comments section

### ISSUE THREAD

**Issue by dumbwanker** [ewhal/nyaa#218]
Might just affect me, but thought I'd raise an issue if not.

Repro:
* [Visit any torrent page](https://nyaa.pantsu.cat/view/923000)
* Click on any number on left of comment, which adds the `comment_x` to the frag
* Said comment may be hidden under header

Also, starting the comment count from zero may be fun and technically correct, but I feel it'll confuse some people. *shrug*

**Comment by egozi44** [comment]
They also look like a mess atm unlike the old nyaa, any chance you will improve them so they will be more comfortable to the eye? They easily get mixed in my eyes when I use monitor with 1080p resolution

**Comment by aerojun** [comment]
I could try modifiying it after work. Can you give me some ideas?

**Comment by egozi44** [comment]
Well the old nyaa design was actually nice (though I may say it because I already got used to it for years), 
![nyaacommenting](https://cloud.githubusercontent.com/assets/14190834/25925555/fe919c90-35f1-11e7-86d5-a58f88a416ac.jpg)

There was enough signs to let you distinguish what commit belong to who:
1. Enough space between each commit.
2. Separation boxs/lines.
3. Numbers.
4. Avatars (if you plan to readd Gavatar support it will be great)
5. A color that appear to show recent commit (usually was displayed only after the use reply and dissapper after good reload)

These days many sites uses similat designs since it sort of comfortable 
![645](https://cloud.githubusercontent.com/assets/14190834/25925661/98ca9f0a-35f2-11e7-8f0a-ee7d3dac9ceb.PNG)

But if you want to think on something unique we can probably thing on something I guess
