### ISSUE TITLE
Moderation and Report System

### ISSUE THREAD

**Issue by S0X-LT** [ewhal/nyaa#35]
Before enabling upload, there NEEDS to be a report system to prevent random people from uploading trash to the site, and a Moderator Team to oversee said system.

Preferably not the old team from Nyaa, they are quite "famous", and some torrents they marked as "A+" (blue) are actually troll translations.

*cough* maybe someone willing to comb through reports *cough*

**Comment by avail** [comment]
I nominate myself!

**Comment by gensuihime** [comment]
As a feature a modsystem is likely a must, but a "modteam" discussion would likely be left best to the owner of the server running the instance of nyaapantsu (unless you're talking specifically about pantsucat, in which case I volunteer to sift thru thousands of tickets because ynot)

Maybe something similar to how 4chan's mod system is built, with a separate page for moderation and other statistics pushed directly to that frontend.

**Comment by ayame-git** [comment]
It's a feature now, yaay!!!
