### ISSUE TITLE
Atom-conformant RSS feeds

### ISSUE THREAD

**Issue by bittebitte** [ewhal/nyaa#544]
RSS feeds should conform to Atom Syndication Format.

`<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">`

**Comment by ewhal** [comment]
Should be fixed.
Will be deploying the changes later.

**Comment by erengy** [comment]
@ewhal Could you revert b6fc7866aae3432876985b466143300aa8671c34, please? `feed.ToAtom()` returns an entirely different output than `feed.ToRss()`. In other words, your RSS feed is no longer an RSS feed. It's an Atom feed, rather than an Atom-conformant RSS feed as requested.

`/feed` route is currently described as "RSS" and linked with the `application/rss+xml` MIME type, which makes things inconsistent throughout the website and problematic for certain feed readers.
